# Netlify配置文件
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # 构建命令
  command = "pnpm build"
  
  # 发布目录
  publish = "dist"
  
  # 函数目录
  functions = "netlify/functions"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  
  # pnpm版本
  PNPM_VERSION = "8"

# ==================== 重定向规则 ====================

# SPA fallback - 所有路由重定向到index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ==================== 头部设置 ====================

[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CSP（内容安全策略）
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self';
      connect-src 'self' https://*.supabase.co;
      frame-ancestors 'none';
    """
    
    # Permissions Policy
    Permissions-Policy = """
      camera=(),
      microphone=(),
      geolocation=(),
      payment=()
    """

# 静态资源缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 图片缓存
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# HTML不缓存
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# ==================== 插件配置 ====================

# 表单处理
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# ==================== 开发环境配置 ====================

[dev]
  # 本地开发服务器端口
  port = 8888
  
  # 目标端口（Astro dev server）
  targetPort = 4321
  
  # 自动打开浏览器
  autoLaunch = false

# ==================== 部署上下文 ====================

[context.production]
  command = "pnpm build"
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  command = "pnpm build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  command = "pnpm build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
